language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
matrix:
  fast_finish: true
before_script:
- composer self-update
- composer install
script: phpunit --configuration phpunit.xml --coverage-text
env:
  matrix:
  - secure: rGutK5OT7tJuW2POP9F31OmKKQNVOlepADGiemBlcJk16kEYu4WBPcrTiYHZ+CN8roSkbC0w+Vjwbot0/QY7Vw9kdKYu+1emoYlYxj3e53hKvEgNIBfIsX9LokL5sk6XYebrE8kUa0BSYEwGD4gaYwLJxTkOIr+050YerpB8laspAv/CMG8PC/n+RQAwGb0rK9QQvMkCHGjcevA7Nk5wwEOSWZEmOpQ9cM15aifAH+bP3p3T6ZiHdSbPP6aBIgsdW/awfimHfBZmrHW6RnNwP4PiEgSYS4zP7p7CimpisTGTMgy5kHMrZTxUZvFbDpnpPyM1zajK1NHp6fx3m/oY+DnSuPs8iC30S99kDiqhscoO40ufTCvHF3X+yVwx2FZd1MWEs2klVksx8QDDel89+JeFQ2MA7ZIof7QYFa7dsKID9rZLq4+kz/2zhMahyUvmuJ5FWsnEZNyjJLPjYBsgIMkZOar4AT+hGLB+DOYkiwJXxSmodftzo3vau7dDo/XcG055gbSGaWKdKmCkf5ixl+iUpCH60E8qVV48mAnFqnlFDxjVCcNwDRM/CCMHv1asjnaPyah4NmIgksqkubJsk2FR6lGzjdZjK5kSn/ECwjeW9iu6ghej+HaST0zDqEtSMwnrArPWJhVSKIbBzlg9uPAyRJ5/bccSSZqXJQTcdyo=
  - secure: WPyxu4oOKOryv5vrkEMXjZZUSfPS7OQPv9W5DVOzb66WpObCWn+f03+RCUhS7fRDtoK68RDMS51WJFCjG26czVvSFCIYOHF6jrQt+yKOQ/v+7Veor9iFyDX4ntYAPqkWG4KJaBZYU2NTOVf4jQsh+Yf8MLF+BBXKBKxKLnukjz8O6/6oTSYJrRngm31bVcmGxjFOquV6pzSetb3WuFGznoLsS3KAIj8K9dVeZLy5V2JIz8Cxx1R2IikWTLpCqLwD4USDIXjW2OA7nARAXis06YseRpTKJXJ0tYj4ZGdHqjV5ywCm7it8FtJSIoMmj4ifjRHVN7OuM2PPAs9gC33nKyxAi4c/vZbRdDBTWjuNcQwxbvJyQ1Bn3PM4UYxz8XEJchubAarSgZ4UQv4iBEY1Klo1R2z9/rFxoddSnDxwZ44qifEbA4IlXShuLYpyB+6q8Ik2RnG66f3jCJDpmrASSD/tQrGvIStgY3uA3rkLiNTEXm8rlJz9AZwM6ZrBgXaHEvtFdWHwqzrIaK+heyWxYrpO1dpGdJv4dbEzB5L4d88n6FIU89Qr7yIP/YyZx1rPO2x2CimmCWUyk6r0ldimrR+ymZy0nM+o1Md1YlPKvGA5DzTHVY5zf97eGPlTU0aMNDalStxDl7YZmN9Bu/UVqw0F9rmMbmj/2rc9XtFcaEA=
